#!/usr/bin/env ruby
require 'chef'
require_relative './library'

opts = LazyOpt.new(__FILE__)
opts.add(:version, 'v', 'version', 'Chef Cookbook Version To Pin', false)
opts.parse!

if opts[:version] == '0.0.0'
	puts 'match'
else
	puts 'no match'
end
