#!/opt/chefdk/embedded/bin/ruby
require 'gitlab'
require 'pp'

def project_status(namespace, project)
  begin
    @project_status ||= client.project("#{namespace}/#{project}")
  rescue Gitlab::Error::NotFound
    pp @project_status
    return nil
  end
  @project_status
end

def client
  @client ||= Gitlab.client(endpoint: 'https://git-staging.nonprod.dots.vip.nordstrom.com/api/v4', private_token: @token)
end


@token = `knife vault show restaurant gitlab_staging | awk '/key:/ {print $2}'`.chomp
namespace = 'chef/cookbooks'
project = 'testbook'
pp project_status(namespace, project)
